In [7]:
my_list = [1,2,3]

In [9]:
my_list

[1, 2, 3]

In [11]:
import numpy as np

In [13]:
np.array(my_list)

array([1, 2, 3])

In [15]:
my_mat = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [17]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# Arange

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#aray of zeros at x lengh
np.zeros(3)

array([0., 0., 0.])

In [31]:
#aray of 1s at x length
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
#create matrix (rows, columns)
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
# Create Random Data

In [45]:
np.random.rand(5)

array([0.6885163 , 0.40389285, 0.61693043, 0.6596294 , 0.60063625])

In [47]:
np.random.rand(5,5)

array([[1.71549597e-01, 8.80459979e-01, 9.13359491e-02, 8.38700669e-01,
        1.99633646e-01],
       [5.46644979e-01, 5.33795454e-04, 4.06834420e-01, 1.84142901e-01,
        2.21811563e-01],
       [5.89921292e-01, 5.51468209e-01, 5.31128449e-02, 5.53442905e-01,
        4.47650990e-01],
       [8.18782887e-01, 8.45639125e-01, 5.61852219e-01, 4.30311043e-01,
        2.55231549e-01],
       [8.49839619e-01, 2.66789615e-01, 3.64908808e-02, 1.32890957e-02,
        9.51345784e-01]])

In [51]:
# returns standard normal distribuion
np.random.randn(2)

array([ 0.19254988, -2.08815771])

In [55]:
#random int value in range
np.random.randint(1,100)

25

In [58]:
arr = np.arange(25)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
ranarr = np.random.randint(0, 50, 10)

In [66]:
ranarr

array([11, 45, 42,  3,  5, 32, 23, 31, 29,  3])

In [74]:
#structures values into a matrix of x,y size
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
#max
ranarr.max()

45

In [78]:
#returns location of value
ranarr.argmax()

1

In [80]:
#get shape
arr.shape

(25,)

In [88]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [92]:
arr.dtype

dtype('int32')

## Numpy Aray Indexing

In [95]:
arr = np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
#works just like list
arr[2]

2

In [103]:
arr[1:5]

array([1, 2, 3, 4])

In [105]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [108]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [112]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [116]:
# Numpy list can brodcast

In [118]:
arr[0:5] = 100

In [120]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [147]:
#reset
arr = np.arange(0,11)

In [149]:
slice_of_arr = arr[0:6]

In [151]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

# Numpy does not set copies of arrays

In [154]:
slice_of_arr[:] = 99

In [156]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [158]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# copy to change numpy arrays

In [161]:
arr_copy = arr.copy()

In [163]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [165]:
arr_copy[:] = 100

In [167]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [169]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# reset

In [183]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [185]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [187]:
arr_2d[0]

array([ 5, 10, 15])

In [200]:
arr_2d[0,1]

10

In [208]:
#grab subset
#[row, column]
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [210]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

# Conditional Selction

In [219]:
arr = np.arange(1,11)

In [221]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [225]:
bool_arr = arr > 5

In [227]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [229]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [231]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Numpy Operations

In [238]:
arr = np.arange(0,11)

In [240]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [242]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [246]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [248]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [252]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [254]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [256]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [258]:
1/0

ZeroDivisionError: division by zero

In [262]:
arr/arr

C:\Users\Admin\AppData\Local\Temp\ipykernel_50776\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [264]:
1/arr

C:\Users\Admin\AppData\Local\Temp\ipykernel_50776\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [266]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# universal array functions

In [269]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [271]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [275]:
np.max(arr)

10

In [277]:
np.log(arr)

C:\Users\Admin\AppData\Local\Temp\ipykernel_50776\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])